---
openapi: "3.0.1"
info:
  title: "Tracked Config Files"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/tracked_config_files/compare_by_change_time:
    get:
      description: "Compare contents of tracked config file around time of change"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            text/html: {}
  /api/now/tracked_config_files/compare_by_two_times:
    get:
      description: "Compare two contents of tracekd configuration file by 2 given\
        \ times"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            text/html: {}
  /api/now/tracked_config_files/diff_audit:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            text/html: {}
  /api/now/tracked_config_files/get_file_content:
    get:
      description: "Get content of tracked configuration file at specified time"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            text/plain: {}
