---
openapi: "3.0.1"
info:
  title: "Application Service"
  description: "Create, update or retrieve application services. Limited to manual\
    \ services only"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/cmdb/app_service/convertToDynamicService:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/app_service/convertToManualService:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/app_service/create:
    post:
      description: "Create or update an application service, including connections\
        \ between CIs"
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/app_service/createDynamicService:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/app_service/updateDynamicNumberOfLevels:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/app_service/{sys_id}/getContent:
    get:
      description: "Get the content of an application service including connections\
        \ between CIs"
      parameters:
      - name: "sys_id"
        in: "path"
        required: true
        schema: {}
      - name: "mode"
        in: "query"
        description: "get minimum or full details of each CI (shallow or full)"
        required: false
        schema: {}
        example: "full"
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/csdm/app_service/find_service:
    get:
      description: ""
      parameters:
      - name: "name"
        in: "query"
        description: "Criteria for finding Application Services"
        required: false
        schema: {}
        example: "testService"
      - name: "number"
        in: "query"
        description: "Numer field on Application Service"
        required: false
        schema: {}
        example: "SNSVC0001018"
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/csdm/app_service/register_service:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/csdm/app_service/{service_sys_id}/populate_service:
    put:
      description: ""
      parameters:
      - name: "service_sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/cmdb/csdm/app_service/{service_sys_id}/service_details:
    put:
      description: ""
      parameters:
      - name: "service_sys_id"
        in: "path"
        required: true
        schema: {}
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
