---
openapi: "3.0.1"
info:
  title: "CSDM Application Service (Internal API)"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/csdm_app_service/ci_types:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/create_app_service:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/delete_app_service:
    delete:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/environment_choice_list:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/get_app_service:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/get_cis_for_tags:
    put:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/get_tag_value_list:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/operational_status_choice_list:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/relation:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_cmdb_groups:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_groups:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_manual_ci:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_model_id:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_product_models:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/search_users:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/tag_based_service_candidates:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/tag_based_service_families:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/tag_based_service_family_category:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/update_app_service:
    put:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/validate_app_service:
    put:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/validate_entry_point:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/csdm_app_service/validate_tag_list:
    put:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
