---
openapi: "3.0.1"
info:
  title: "Application Service Internal API"
  description: "Create, update or retreive the content of an application service"
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/it_service/addBaseline:
    get:
      description: "Adds new baseline to history timeline of given service"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            text/plain: {}
  /api/now/it_service/bsData:
    get:
      description: "Get proeprteis of service for current/history map view."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/ciFullData:
    get:
      description: "Get properties for CI in current/historical map view"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/compareBsData:
    get:
      description: "Service properties for comparison map."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/compareCiFullData:
    get:
      description: "Ci properties for comparison map."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/compareEdgesData:
    post:
      description: "Edges properties for comparison map."
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/compareService:
    get:
      description: "Get comparison map for service (map json)."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/edgesData:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getAllBSPreferences:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getBSPreference:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getBaselines:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getParentServices:
    post:
      description: ""
      parameters: []
      requestBody:
        content:
          application/json: {}
          application/xml: {}
          text/xml: {}
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getServiceTimeline:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/getServiceTimelineCheckpoints:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/isChanged:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/map:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/mapNotifications:
    get:
      description: "Get map notifications for UI. Currently supports single notification\
        \ at time"
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/map_api:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/processDataFromGenericAppl:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/relatedItemsFullData:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/removeBaseline:
    get:
      description: "Removes baseline from history timeline, by baseline sys_id."
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/serviceTreeData:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/setBSPreference:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/updateBaseline:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
  /api/now/it_service/wasTableUpdatedSince:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
