---
openapi: "3.0.1"
info:
  title: "VA Web Client Settings"
  description: ""
  version: "latest"
externalDocs:
  url: ""
servers:
- url: "https://dev272070.service-now.com/"
paths:
  /api/now/va_web_client_settings/get_va_web_client_settings:
    get:
      description: ""
      parameters: []
      responses:
        "200":
          description: "ok"
          content:
            application/json: {}
            application/xml: {}
            text/xml: {}
